site_name: Astral

nav:
    - Info: 
        - Home: info/index.md
        - About: info/about.md
        - Release Notes: info/release_notes.md
        - Contact: info/contact.md
        
    - Model:
        - 2D Aerodinamic Models: model/2d_aerodyncamid_model.md
        - Atmospheric Model: model/atmospheric_model.md

    - App:
        - Intro: app/intro.md
        - How to Install: app/how_to_install.md
        - How to Use: app/how_to_use.md
        - Interface Options: app/interface_options.md

        


theme:
  name: readthedocs


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
